export const GET_STAFF_REQUEST = 'GET_STAFF_REQUEST'
export const GET_STAFF_SUCCESS = 'GET_STAFF_SUCCESS'
export const GET_STAFF_FAILED = 'GET_STAFF_FAILED'
export const GET_STAFF_RESET = 'GET_STAFF_RESET'

export const CREATE_STAFF_REQUEST = 'CREATE_STAFF_REQUEST'
export const CREATE_STAFF_SUCCESS = 'CREATE_STAFF_SUCCESS'
export const CREATE_STAFF_FAILED = 'CREATE_STAFF_FAILED'
export const CREATE_STAFF_RESET = 'CREATE_STAFF_RESET'

export const LOGIN_STAFF_REQUEST = 'LOGIN_STAFF_REQUEST'
export const LOGIN_STAFF_SUCCESS = 'LOGIN_STAFF_SUCCESS'
export const LOGIN_STAFF_FAILED = 'LOGIN_STAFF_FAILED'
export const LOGIN_STAFF_RESET = 'LOGIN_STAFF_RESET'

export const LOGOUT_STAFF = 'LOGOUT_STAFF'