export const GET_TASK_REQUEST = 'GET_TASK_REQUEST'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const GET_TASK_FAILED = 'GET_TASK_FAILED'
export const GET_TASK_RESET = 'GET_TASK_RESET'

export const GET_ALLTASK_REQUEST = 'GET_ALLTASK_REQUEST'
export const GET_ALLTASK_SUCCESS = 'GET_ALLTASK_SUCCESS'
export const GET_ALLTASK_FAILED = 'GET_ALLTASK_FAILED'
export const GET_ALLTASK_RESET = 'GET_ALLTASK_RESET'

export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST'
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS'
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED'
export const ADD_TASK_RESET = 'ADD_TASK_RESET'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILED = 'UPDATE_TASK_FAILED'
export const UPDATE_TASK_RESET = 'UPDATE_TASK_RESET'

export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED'
export const DELETE_TASK_RESET = 'DELETE_TASK_RESET'

